do_train: False
do_local: False
epochs: 50
gpu: 1
data_folder: "data/muc_sentence"
save_model_folder: "models/"
save_model_filename: "best-summarizer"
batch_size: 10
workers: 12
max_token_len: 512
warmup_steps: 20
pretrained_path: "s3://experiment-logging/storage/ContextSum/train.bf861489e1aa487abfbbf8728fbf0947/models/epoch=1-step=957.ckpt"

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null