do_train: True
do_local: True
epochs: 1
gpu: 1
data_folder: "data/muc_sentence"
save_model_folder: "models/"
save_model_filename: "best-summarizer"
batch_size: 1
workers: 12
max_token_len: 512
warmup_steps: 20

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null